---

# - name: Add required apt repositories
#   apt_repository:
#     repo: "{{ item }}"
#     state: present
#   with_items: "{{ apt_repos_to_install }}"
#   ignore_errors: yes

- name: Install required docker apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages_for_docker }}"
  ignore_errors: yes

- name: Get docker signing key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: Add docker apt repository
  shell: sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"

- name: Update apt cache
  apt: 
    update_cache: yes

- name: Install required apt packages
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ apt_packages_to_install }}"
  ignore_errors: yes

- name: Remove unrequired apt packages
  apt:
    name: "{{ item }}"
    state: absent
  with_items: "{{ apt_packages_to_remove }}"
  ignore_errors: yes

- name: Add user to docker group
  shell: sudo usermod -aG docker $USER