---

- set_fact:
   templates_destination: /
   templates_source: '{{ playbook_dir }}/roles/config-files/templates/'
   files_source: '{{ playbook_dir }}/roles/config-files/files/'

- name: Copy over all service-specific static files
  synchronize:
    src: '{{ files_source }}'
    dest: '{{ templates_destination }}'
  ignore_errors: yes

- name: Create directories for templateable files
  file:
    state: directory
    dest: '{{ templates_destination }}{{ item.path }}'
  with_filetree: '{{ templates_source }}'
  when: item.state == 'directory'

- name: Ensure any templateable files are populated from templates
  template:
    src: '{{ item.src }}'
    dest: '{{ templates_destination }}{{ item.path }}'
  with_filetree: '{{ templates_source }}'
  when: item.state == 'file'

- name: Move all files within fake user directory to current user directory
  synchronize:
    src: /home/user/
    dest: /home/{{ username_on_the_host }}/
  ignore_errors: yes

- name: Remove fake user directory
  file: 
    path: /home/user/
    state: absent